import "dotenv/config";
import { TicketCategory, TicketStatus } from "../src/generated/prisma/enums";
import { prisma } from "../src/db";

const tickets: {
  subject: string;
  body: string;
  status: TicketStatus;
  category: TicketCategory | null;
  senderName: string;
  senderEmail: string;
  createdAt: Date;
}[] = [
  // --- Refund Requests ---
  {
    subject: "Refund request for order #10482",
    body: "Hi, I ordered a pair of running shoes last week but received the wrong size. I'd like a full refund. Order #10482.",
    status: TicketStatus.Open,
    category: TicketCategory.Refund_Request,
    senderName: "Alice Johnson",
    senderEmail: "alice.johnson@gmail.com",
    createdAt: daysAgo(1),
  },
  {
    subject: "Double charged for subscription",
    body: "I was billed twice for my monthly subscription in November. Please refund the duplicate charge of $29.99.",
    status: TicketStatus.Resolved,
    category: TicketCategory.Refund_Request,
    senderName: "Marcus Webb",
    senderEmail: "marcus.webb@outlook.com",
    createdAt: daysAgo(3),
  },
  {
    subject: "Product arrived damaged — need refund",
    body: "My order arrived with a cracked screen protector. The packaging was also torn. I want a refund or replacement ASAP.",
    status: TicketStatus.Open,
    category: TicketCategory.Refund_Request,
    senderName: "Priya Sharma",
    senderEmail: "priya.sharma@yahoo.com",
    createdAt: daysAgo(2),
  },
  {
    subject: "Cancelled order still pending refund",
    body: "I cancelled my order 10 days ago and was told the refund would arrive within 5-7 business days. Still nothing.",
    status: TicketStatus.Open,
    category: TicketCategory.Refund_Request,
    senderName: "Derek Olsen",
    senderEmail: "derek.olsen@hotmail.com",
    createdAt: daysAgo(10),
  },
  {
    subject: "Refund for unused annual plan",
    body: "I upgraded to the annual plan by mistake. I only intended to renew monthly. Can I get a prorated refund?",
    status: TicketStatus.Closed,
    category: TicketCategory.Refund_Request,
    senderName: "Sophie Laurent",
    senderEmail: "sophie.laurent@gmail.com",
    createdAt: daysAgo(20),
  },
  {
    subject: "Wrong item delivered, want refund",
    body: "I ordered a blue jacket (size M) but received a red one in XL. I don't want an exchange — just a full refund.",
    status: TicketStatus.Resolved,
    category: TicketCategory.Refund_Request,
    senderName: "James Okafor",
    senderEmail: "j.okafor@proton.me",
    createdAt: daysAgo(7),
  },
  {
    subject: "Refund for event ticket — event cancelled",
    body: "The webinar I signed up for on December 3rd was cancelled with no notice. Please refund my $49 registration fee.",
    status: TicketStatus.Open,
    category: TicketCategory.Refund_Request,
    senderName: "Nina Patel",
    senderEmail: "nina.patel@icloud.com",
    createdAt: daysAgo(5),
  },
  {
    subject: "Subscription refund — charged after cancellation",
    body: "I cancelled my account on October 31st but was still charged on November 1st. Please refund the $14.99.",
    status: TicketStatus.Resolved,
    category: TicketCategory.Refund_Request,
    senderName: "Tom Eriksson",
    senderEmail: "tom.eriksson@gmail.com",
    createdAt: daysAgo(15),
  },
  {
    subject: "Item not as described — requesting refund",
    body: "The laptop stand I purchased was described as 'aluminum' but arrived in plastic. Very misleading. Requesting a refund.",
    status: TicketStatus.Closed,
    category: TicketCategory.Refund_Request,
    senderName: "Fatima Al-Rashid",
    senderEmail: "fatima.rashid@gmail.com",
    createdAt: daysAgo(30),
  },
  {
    subject: "Gift card balance disappeared",
    body: "I had $80 in gift card credit that has vanished from my account. Please restore or refund the balance.",
    status: TicketStatus.Open,
    category: TicketCategory.Refund_Request,
    senderName: "Leo Nguyen",
    senderEmail: "leo.nguyen@yahoo.com",
    createdAt: daysAgo(4),
  },

  // --- Technical Questions ---
  {
    subject: "Cannot log in — password reset not working",
    body: "I reset my password but the link in the email doesn't work. I've tried 3 times now. Browser: Chrome 120.",
    status: TicketStatus.Open,
    category: TicketCategory.Technical_Question,
    senderName: "Rachel Kim",
    senderEmail: "rachel.kim@gmail.com",
    createdAt: daysAgo(1),
  },
  {
    subject: "App crashing on iOS 17 after update",
    body: "Since the latest app update (v3.2.1) the app crashes every time I open the notification center. iPhone 14 Pro.",
    status: TicketStatus.Open,
    category: TicketCategory.Technical_Question,
    senderName: "Connor Walsh",
    senderEmail: "connor.walsh@icloud.com",
    createdAt: daysAgo(2),
  },
  {
    subject: "Two-factor authentication codes not arriving",
    body: "I enabled 2FA last week but the SMS codes never arrive. I've verified my phone number is correct (+1 415 555 0193).",
    status: TicketStatus.Resolved,
    category: TicketCategory.Technical_Question,
    senderName: "Yuki Tanaka",
    senderEmail: "yuki.tanaka@gmail.com",
    createdAt: daysAgo(6),
  },
  {
    subject: "API rate limit hit unexpectedly",
    body: "Our integration is hitting the 1000 req/min limit but our dashboard shows only 200 requests. Something looks off.",
    status: TicketStatus.Open,
    category: TicketCategory.Technical_Question,
    senderName: "Arjun Mehta",
    senderEmail: "arjun.mehta@techcorp.io",
    createdAt: daysAgo(1),
  },
  {
    subject: "Export to CSV not working",
    body: "When I click 'Export CSV' on the reports page, I get a blank download. This worked fine last month.",
    status: TicketStatus.Resolved,
    category: TicketCategory.Technical_Question,
    senderName: "Claire Dubois",
    senderEmail: "claire.dubois@example.fr",
    createdAt: daysAgo(8),
  },
  {
    subject: "Webhook not firing on order completion",
    body: "I've configured the order.completed webhook endpoint but events are not being delivered. Verified the URL is correct.",
    status: TicketStatus.Open,
    category: TicketCategory.Technical_Question,
    senderName: "Samuel Reyes",
    senderEmail: "samuel.reyes@devteam.com",
    createdAt: daysAgo(3),
  },
  {
    subject: "Dark mode flicker on page load",
    body: "When dark mode is enabled the page briefly flashes white before applying the dark theme. Very jarring.",
    status: TicketStatus.Closed,
    category: TicketCategory.Technical_Question,
    senderName: "Ingrid Larsen",
    senderEmail: "ingrid.larsen@nordic.no",
    createdAt: daysAgo(45),
  },
  {
    subject: "SSO login redirect loop",
    body: "After setting up SAML SSO with Okta, users are stuck in a redirect loop. Error code: ERR_TOO_MANY_REDIRECTS.",
    status: TicketStatus.Open,
    category: TicketCategory.Technical_Question,
    senderName: "Michael Torres",
    senderEmail: "m.torres@enterprise.com",
    createdAt: daysAgo(2),
  },
  {
    subject: "Images not loading in Firefox",
    body: "Product images are broken only in Firefox (v120). They load fine in Chrome and Safari. Console shows CORS errors.",
    status: TicketStatus.Resolved,
    category: TicketCategory.Technical_Question,
    senderName: "Hannah Schmidt",
    senderEmail: "h.schmidt@web.de",
    createdAt: daysAgo(12),
  },
  {
    subject: "Search returning no results despite matching items",
    body: "Searching for 'wireless headphones' returns 0 results even though I can see the product in the catalog.",
    status: TicketStatus.Open,
    category: TicketCategory.Technical_Question,
    senderName: "Brandon Lee",
    senderEmail: "brandon.lee@gmail.com",
    createdAt: daysAgo(1),
  },
  {
    subject: "Mobile checkout freezes at payment step",
    body: "On Android (Samsung Galaxy S23), the checkout freezes after entering card details. The spinner just keeps going.",
    status: TicketStatus.Open,
    category: TicketCategory.Technical_Question,
    senderName: "Amara Diallo",
    senderEmail: "amara.diallo@gmail.com",
    createdAt: daysAgo(3),
  },
  {
    subject: "Bulk import CSV failing with error 500",
    body: "Trying to import 2,000 contacts via CSV. Upload completes but then I get a 500 error. File attached.",
    status: TicketStatus.Open,
    category: TicketCategory.Technical_Question,
    senderName: "Paul Fitzgerald",
    senderEmail: "paul.fitz@salesteam.com",
    createdAt: daysAgo(2),
  },
  {
    subject: "Email notifications sending duplicates",
    body: "Every order confirmation is being sent twice to customers. Started happening after the Nov 15 deployment.",
    status: TicketStatus.Resolved,
    category: TicketCategory.Technical_Question,
    senderName: "Elena Vasquez",
    senderEmail: "elena.vasquez@shop.com",
    createdAt: daysAgo(18),
  },
  {
    subject: "Charts not rendering on dashboard",
    body: "The sales charts on the analytics dashboard are blank. I see a loading spinner that never stops. Chrome + Windows 11.",
    status: TicketStatus.Closed,
    category: TicketCategory.Technical_Question,
    senderName: "Omar Hassan",
    senderEmail: "omar.hassan@analytics.co",
    createdAt: daysAgo(60),
  },
  {
    subject: "Can't upload profile picture larger than 1MB",
    body: "The profile picture upload fails for any file over 1MB. Your docs say limit is 5MB. Is there a bug?",
    status: TicketStatus.Resolved,
    category: TicketCategory.Technical_Question,
    senderName: "Julia Chen",
    senderEmail: "julia.chen@icloud.com",
    createdAt: daysAgo(9),
  },
  {
    subject: "Zapier integration not authenticating",
    body: "The Zapier app keeps saying 'invalid API key' even though I've regenerated and re-entered the key three times.",
    status: TicketStatus.Open,
    category: TicketCategory.Technical_Question,
    senderName: "Ryan Murphy",
    senderEmail: "ryan.murphy@startupco.com",
    createdAt: daysAgo(4),
  },
  {
    subject: "Report generation timeout for large date ranges",
    body: "Generating a report for the full year 2023 times out after 30 seconds. Smaller ranges work fine.",
    status: TicketStatus.Open,
    category: TicketCategory.Technical_Question,
    senderName: "Nadia Kowalski",
    senderEmail: "nadia.k@business.pl",
    createdAt: daysAgo(5),
  },
  {
    subject: "Push notifications not working after reinstall",
    body: "After uninstalling and reinstalling the app, I no longer receive push notifications on my iPhone 13.",
    status: TicketStatus.Resolved,
    category: TicketCategory.Technical_Question,
    senderName: "Caleb Wright",
    senderEmail: "caleb.wright@gmail.com",
    createdAt: daysAgo(14),
  },
  {
    subject: "Error when saving custom domain",
    body: "I enter my domain and click save but get 'Invalid domain format' even though the domain is valid and DNS is configured.",
    status: TicketStatus.Open,
    category: TicketCategory.Technical_Question,
    senderName: "Isabelle Martin",
    senderEmail: "isabelle.martin@agence.fr",
    createdAt: daysAgo(2),
  },
  {
    subject: "Account locked after failed login attempts",
    body: "My account got locked after 3 failed attempts (fat-fingered password). How do I unlock it without resetting?",
    status: TicketStatus.Resolved,
    category: TicketCategory.Technical_Question,
    senderName: "David Park",
    senderEmail: "david.park@korea.kr",
    createdAt: daysAgo(11),
  },

  // --- General Questions ---
  {
    subject: "How do I upgrade my plan?",
    body: "I'm on the Starter plan and want to move to Professional. I can't find the upgrade option in my account settings.",
    status: TicketStatus.Resolved,
    category: TicketCategory.General_Question,
    senderName: "Emma Thornton",
    senderEmail: "emma.thornton@gmail.com",
    createdAt: daysAgo(4),
  },
  {
    subject: "Do you offer a non-profit discount?",
    body: "We're a registered 501(c)(3) charity. Do you have special pricing for non-profit organizations?",
    status: TicketStatus.Open,
    category: TicketCategory.General_Question,
    senderName: "Robert Grant",
    senderEmail: "robert.grant@ngohelp.org",
    createdAt: daysAgo(2),
  },
  {
    subject: "What is your data retention policy?",
    body: "We're evaluating your product for GDPR compliance. How long do you retain user data after account deletion?",
    status: TicketStatus.Resolved,
    category: TicketCategory.General_Question,
    senderName: "Annika Bergman",
    senderEmail: "annika.bergman@legal.se",
    createdAt: daysAgo(7),
  },
  {
    subject: "Can I have multiple team members on one account?",
    body: "We're a team of 5. Can we all log in under the same account, or do we need separate seats?",
    status: TicketStatus.Resolved,
    category: TicketCategory.General_Question,
    senderName: "Carlos Mendes",
    senderEmail: "carlos.mendes@studio.pt",
    createdAt: daysAgo(3),
  },
  {
    subject: "Where can I find my invoice?",
    body: "I need a PDF invoice for last month's payment for my company expenses. Where do I download it?",
    status: TicketStatus.Resolved,
    category: TicketCategory.General_Question,
    senderName: "Lily Zhang",
    senderEmail: "lily.zhang@corp.cn",
    createdAt: daysAgo(5),
  },
  {
    subject: "Is there a mobile app available?",
    body: "I've been using the web version and love it. Is there an iOS or Android app I can use on the go?",
    status: TicketStatus.Resolved,
    category: TicketCategory.General_Question,
    senderName: "Patrick O'Brien",
    senderEmail: "patrick.obrien@icloud.com",
    createdAt: daysAgo(9),
  },
  {
    subject: "Do you support custom branding / white-labeling?",
    body: "We'd like to use your platform under our own brand. Is white-labeling available on any plan?",
    status: TicketStatus.Open,
    category: TicketCategory.General_Question,
    senderName: "Simone Rousseau",
    senderEmail: "simone.rousseau@agency.com",
    createdAt: daysAgo(1),
  },
  {
    subject: "How do I change my billing email?",
    body: "The receipts are going to my old email. I updated my account email but invoices still go to the old address.",
    status: TicketStatus.Resolved,
    category: TicketCategory.General_Question,
    senderName: "Victor Osei",
    senderEmail: "victor.osei@work.gh",
    createdAt: daysAgo(6),
  },
  {
    subject: "What payment methods do you accept?",
    body: "I don't have a credit card. Do you accept PayPal, bank transfer, or crypto?",
    status: TicketStatus.Resolved,
    category: TicketCategory.General_Question,
    senderName: "Hana Suzuki",
    senderEmail: "hana.suzuki@outlook.jp",
    createdAt: daysAgo(13),
  },
  {
    subject: "Can I pause my subscription instead of cancelling?",
    body: "I'm going on sabbatical for 3 months and won't need the service. Can I pause rather than cancel?",
    status: TicketStatus.Open,
    category: TicketCategory.General_Question,
    senderName: "Tobias Richter",
    senderEmail: "tobias.richter@gmail.de",
    createdAt: daysAgo(2),
  },
  {
    subject: "Is my data backed up?",
    body: "I accidentally deleted a project. Can data be recovered? What's your backup policy?",
    status: TicketStatus.Resolved,
    category: TicketCategory.General_Question,
    senderName: "Chioma Adeyemi",
    senderEmail: "chioma.adeyemi@ng.com",
    createdAt: daysAgo(8),
  },
  {
    subject: "Do you have a status page for outages?",
    body: "The service seemed slow yesterday. Is there somewhere I can check for real-time status and incident history?",
    status: TicketStatus.Resolved,
    category: TicketCategory.General_Question,
    senderName: "Ethan Brooks",
    senderEmail: "ethan.brooks@gmail.com",
    createdAt: daysAgo(16),
  },
  {
    subject: "How long does shipping take to Canada?",
    body: "I'm in Toronto. What's the estimated delivery time and shipping cost for orders to Canada?",
    status: TicketStatus.Resolved,
    category: TicketCategory.General_Question,
    senderName: "Mei Lin",
    senderEmail: "mei.lin@canada.ca",
    createdAt: daysAgo(11),
  },
  {
    subject: "Do you offer annual billing with a discount?",
    body: "I've been on monthly billing. Is there a discount if I switch to annual? How much would I save?",
    status: TicketStatus.Resolved,
    category: TicketCategory.General_Question,
    senderName: "Alessandro Ferrari",
    senderEmail: "a.ferrari@studio.it",
    createdAt: daysAgo(22),
  },
  {
    subject: "Can I transfer my account to another person?",
    body: "I'm selling my business and need to transfer the account to the new owner. Is that possible?",
    status: TicketStatus.Open,
    category: TicketCategory.General_Question,
    senderName: "Grace Williams",
    senderEmail: "grace.williams@business.au",
    createdAt: daysAgo(3),
  },
  {
    subject: "Do you have an affiliate or referral program?",
    body: "I love the product and recommend it often. Is there a referral program where I can earn credits?",
    status: TicketStatus.Open,
    category: TicketCategory.General_Question,
    senderName: "Felix Müller",
    senderEmail: "felix.mueller@gmail.de",
    createdAt: daysAgo(4),
  },
  {
    subject: "Are there volume discounts for 50+ seats?",
    body: "We're planning to onboard our whole sales team (around 60 people). Do you offer enterprise or volume pricing?",
    status: TicketStatus.Open,
    category: TicketCategory.General_Question,
    senderName: "Samantha Cole",
    senderEmail: "s.cole@enterprise.us",
    createdAt: daysAgo(1),
  },
  {
    subject: "What happens to my data if I cancel?",
    body: "If I cancel my subscription, how long do you keep my data? Can I export everything before it's deleted?",
    status: TicketStatus.Resolved,
    category: TicketCategory.General_Question,
    senderName: "Ravi Kapoor",
    senderEmail: "ravi.kapoor@india.in",
    createdAt: daysAgo(19),
  },
  {
    subject: "Do you offer onboarding assistance?",
    body: "Our team is new to the platform. Do you offer guided onboarding, training sessions, or dedicated support?",
    status: TicketStatus.Open,
    category: TicketCategory.General_Question,
    senderName: "Natalie Hughes",
    senderEmail: "natalie.hughes@newco.com",
    createdAt: daysAgo(2),
  },
  {
    subject: "Is the platform available in Spanish?",
    body: "Several of our users are Spanish-speaking. Is a Spanish language option available or planned?",
    status: TicketStatus.Resolved,
    category: TicketCategory.General_Question,
    senderName: "Diego Herrera",
    senderEmail: "diego.herrera@mx.com",
    createdAt: daysAgo(25),
  },
  {
    subject: "Can I use my own SMTP for email sending?",
    body: "I'd like emails to come from my own domain and mail server. Can I configure a custom SMTP?",
    status: TicketStatus.Open,
    category: TicketCategory.General_Question,
    senderName: "Zara Ahmed",
    senderEmail: "zara.ahmed@startup.pk",
    createdAt: daysAgo(3),
  },

  // --- Mix: more open, recent, diverse senders ---
  {
    subject: "Discount code not applying at checkout",
    body: "I have the promo code SAVE20 but it says 'code not valid' when I try to use it. It should be valid until Dec 31.",
    status: TicketStatus.Open,
    category: TicketCategory.General_Question,
    senderName: "Olivia Turner",
    senderEmail: "olivia.turner@gmail.com",
    createdAt: daysAgo(1),
  },
  {
    subject: "Order tracking link shows no updates",
    body: "My order shipped 4 days ago but the tracking link just says 'label created'. Is there a delay with the carrier?",
    status: TicketStatus.Open,
    category: TicketCategory.General_Question,
    senderName: "Noah Martinez",
    senderEmail: "noah.martinez@outlook.com",
    createdAt: daysAgo(4),
  },
  {
    subject: "Database connection error in integration",
    body: "Getting 'connection refused' when our server tries to connect to your data sync endpoint. Started yesterday.",
    status: TicketStatus.Open,
    category: TicketCategory.Technical_Question,
    senderName: "Aisha Kamara",
    senderEmail: "aisha.kamara@devops.io",
    createdAt: daysAgo(1),
  },
  {
    subject: "Session expires too quickly",
    body: "I'm being logged out after ~10 minutes of inactivity. Can the session timeout be extended? Very disruptive.",
    status: TicketStatus.Resolved,
    category: TicketCategory.Technical_Question,
    senderName: "Lucas Petit",
    senderEmail: "lucas.petit@work.fr",
    createdAt: daysAgo(17),
  },
  {
    subject: "Refund for accidental team seat upgrade",
    body: "I accidentally upgraded from 5 to 10 seats. I don't need the extra seats. Can I get a refund for the difference?",
    status: TicketStatus.Open,
    category: TicketCategory.Refund_Request,
    senderName: "Maya Robinson",
    senderEmail: "maya.robinson@team.com",
    createdAt: daysAgo(2),
  },
  {
    subject: "Phone number field not accepting international format",
    body: "The phone field rejects numbers with a + prefix (e.g. +44 7700 900123). It should support international numbers.",
    status: TicketStatus.Closed,
    category: TicketCategory.Technical_Question,
    senderName: "Jack Thompson",
    senderEmail: "jack.thompson@uk.com",
    createdAt: daysAgo(40),
  },
  {
    subject: "Can the system send reminders before subscription renewal?",
    body: "I was surprised by the renewal charge. Can you send an email reminder 7 days before the billing date?",
    status: TicketStatus.Open,
    category: TicketCategory.General_Question,
    senderName: "Valentina Cruz",
    senderEmail: "valentina.cruz@ar.com",
    createdAt: daysAgo(2),
  },
  {
    subject: "Refund request — product didn't meet expectations",
    body: "The software doesn't do what the sales page claims. I've only had it 48 hours. Is there a money-back guarantee?",
    status: TicketStatus.Open,
    category: TicketCategory.Refund_Request,
    senderName: "Liam O'Connor",
    senderEmail: "liam.oconnor@ie.com",
    createdAt: daysAgo(2),
  },
  {
    subject: "Error 403 when accessing shared reports",
    body: "My colleague shared a report link with me but I get a 403 Forbidden error even after logging in.",
    status: TicketStatus.Resolved,
    category: TicketCategory.Technical_Question,
    senderName: "Mia Johansson",
    senderEmail: "mia.johansson@se.com",
    createdAt: daysAgo(10),
  },
  {
    subject: "Invoice shows wrong company name",
    body: "My invoices show my personal name instead of my company name 'Bright Solutions Ltd'. How do I fix this?",
    status: TicketStatus.Resolved,
    category: TicketCategory.General_Question,
    senderName: "William Chen",
    senderEmail: "w.chen@brightsolutions.com",
    createdAt: daysAgo(6),
  },
  {
    subject: "Partial shipment — missing items",
    body: "My order of 3 items only included 2. The third (wireless mouse) is missing. Order #29183.",
    status: TicketStatus.Open,
    category: TicketCategory.General_Question,
    senderName: "Amelia Fox",
    senderEmail: "amelia.fox@personal.com",
    createdAt: daysAgo(3),
  },
  {
    subject: "Slack integration not posting notifications",
    body: "Connected Slack workspace but order notifications aren't appearing in the #orders channel. Token seems valid.",
    status: TicketStatus.Open,
    category: TicketCategory.Technical_Question,
    senderName: "Ben Adams",
    senderEmail: "ben.adams@remoteco.com",
    createdAt: daysAgo(2),
  },
  {
    subject: "Can't delete my account",
    body: "I tried to delete my account from settings but the button is greyed out. I want to exercise my right to erasure.",
    status: TicketStatus.Open,
    category: TicketCategory.Technical_Question,
    senderName: "Lucia Fernandez",
    senderEmail: "lucia.fernandez@es.com",
    createdAt: daysAgo(1),
  },
  {
    subject: "Refund — software incompatible with my system",
    body: "Your desktop app requires macOS 13+ but your website doesn't mention that. I'm on macOS 12. Please refund.",
    status: TicketStatus.Resolved,
    category: TicketCategory.Refund_Request,
    senderName: "Henry Wilson",
    senderEmail: "henry.wilson@mac.com",
    createdAt: daysAgo(12),
  },
  {
    subject: "Two accounts accidentally created",
    body: "I seem to have signed up twice with different emails. Can you merge the accounts or delete the duplicate?",
    status: TicketStatus.Resolved,
    category: TicketCategory.General_Question,
    senderName: "Eva Lindqvist",
    senderEmail: "eva.lindqvist@work.se",
    createdAt: daysAgo(21),
  },
  {
    subject: "Password manager autofill breaking form submission",
    body: "When I use 1Password autofill on the login form, the submit button stays disabled. Manual entry works fine.",
    status: TicketStatus.Closed,
    category: TicketCategory.Technical_Question,
    senderName: "Arthur Dupont",
    senderEmail: "arthur.dupont@fr.com",
    createdAt: daysAgo(55),
  },
  {
    subject: "Confusing checkout flow — need help placing order",
    body: "I'm not sure how to add a gift message during checkout. The option seems to have moved or disappeared.",
    status: TicketStatus.Resolved,
    category: TicketCategory.General_Question,
    senderName: "Rin Yamamoto",
    senderEmail: "rin.yamamoto@jp.com",
    createdAt: daysAgo(14),
  },
  {
    subject: "API keys not showing in dashboard after generation",
    body: "I generated a new API key but it doesn't appear in the list. I've tried refreshing and different browsers.",
    status: TicketStatus.Open,
    category: TicketCategory.Technical_Question,
    senderName: "Chris Nakamura",
    senderEmail: "chris.nakamura@devops.jp",
    createdAt: daysAgo(1),
  },
  {
    subject: "Refund on behalf of a gift recipient",
    body: "I bought this as a gift but the recipient already has one. Can we get a refund even though the order is in my name?",
    status: TicketStatus.Open,
    category: TicketCategory.Refund_Request,
    senderName: "Sarah Bennett",
    senderEmail: "sarah.bennett@gmail.com",
    createdAt: daysAgo(3),
  },
  {
    subject: "How to integrate with Shopify?",
    body: "I'm trying to connect my Shopify store but can't find a Shopify plugin in the integrations page. Is it supported?",
    status: TicketStatus.Resolved,
    category: TicketCategory.Technical_Question,
    senderName: "Adam Clarke",
    senderEmail: "adam.clarke@mystore.com",
    createdAt: daysAgo(9),
  },
  {
    subject: "Billing cycle confused — charged mid-month",
    body: "I signed up on the 14th and expected to be billed monthly from that date. But I was charged again on the 1st.",
    status: TicketStatus.Resolved,
    category: TicketCategory.General_Question,
    senderName: "Fiona MacLeod",
    senderEmail: "fiona.macleod@scot.uk",
    createdAt: daysAgo(28),
  },
  {
    subject: "Need VAT invoice for EU tax compliance",
    body: "I'm based in Germany and need a VAT-compliant invoice with your EU VAT number. The current invoices don't include this.",
    status: TicketStatus.Open,
    category: TicketCategory.General_Question,
    senderName: "Klaus Bauer",
    senderEmail: "k.bauer@firma.de",
    createdAt: daysAgo(2),
  },
  {
    subject: "Video calls not working in Safari",
    body: "The video call feature in the platform doesn't work in Safari 17. Microphone and camera permissions are allowed.",
    status: TicketStatus.Open,
    category: TicketCategory.Technical_Question,
    senderName: "Isla Robertson",
    senderEmail: "isla.robertson@uk.com",
    createdAt: daysAgo(4),
  },
  {
    subject: "Data export format request — Excel instead of CSV",
    body: "The export only gives CSV files. Is there a way to export in .xlsx format directly?",
    status: TicketStatus.Closed,
    category: TicketCategory.General_Question,
    senderName: "Pedro Alves",
    senderEmail: "pedro.alves@empresa.br",
    createdAt: daysAgo(50),
  },
  {
    subject: "Refund for duplicate purchase",
    body: "I bought the same course twice by accident. Transaction IDs: TXN-8821 and TXN-8823. Please refund one.",
    status: TicketStatus.Resolved,
    category: TicketCategory.Refund_Request,
    senderName: "Chloe Anderson",
    senderEmail: "chloe.anderson@edu.com",
    createdAt: daysAgo(16),
  },
  {
    subject: "Can't add a secondary admin to the account",
    body: "I want to give another person admin access. I can see the 'Invite Admin' option but get an error when I submit.",
    status: TicketStatus.Open,
    category: TicketCategory.Technical_Question,
    senderName: "Tariq Al-Amin",
    senderEmail: "tariq.alamin@corp.ae",
    createdAt: daysAgo(2),
  },
  {
    subject: "Time zone settings not saving",
    body: "I set my time zone to GMT+9 (Tokyo) and save, but all times still show in UTC. Tried 3 times.",
    status: TicketStatus.Resolved,
    category: TicketCategory.Technical_Question,
    senderName: "Kenji Watanabe",
    senderEmail: "kenji.watanabe@jp.net",
    createdAt: daysAgo(23),
  },
  {
    subject: "Item returned 2 weeks ago, refund not received",
    body: "I shipped back the item on November 8th with tracking. It was delivered on November 10th. Still no refund.",
    status: TicketStatus.Open,
    category: TicketCategory.Refund_Request,
    senderName: "Jasmine Powell",
    senderEmail: "jasmine.powell@gmail.com",
    createdAt: daysAgo(5),
  },
  {
    subject: "Terms of service question before purchasing",
    body: "Before I subscribe, can you confirm: do you reserve the right to change pricing mid-subscription without notice?",
    status: TicketStatus.Resolved,
    category: TicketCategory.General_Question,
    senderName: "Stefan Novak",
    senderEmail: "stefan.novak@cz.com",
    createdAt: daysAgo(31),
  },
  {
    subject: "Forgot to apply student discount at purchase",
    body: "I have a valid .edu email but forgot to use it at checkout. Can the 30% student discount be applied retroactively?",
    status: TicketStatus.Open,
    category: TicketCategory.Refund_Request,
    senderName: "Imogen Clarke",
    senderEmail: "i.clarke@university.edu",
    createdAt: daysAgo(1),
  },
  {
    subject: "QR code on packaging not working",
    body: "The QR code printed on the product box leads to a 404 page. Should redirect to the setup guide.",
    status: TicketStatus.Open,
    category: TicketCategory.Technical_Question,
    senderName: "Frederic Blanc",
    senderEmail: "frederic.blanc@fr.net",
    createdAt: daysAgo(3),
  },
  {
    subject: "Feature request — bulk actions in ticket list",
    body: "It would be great to select multiple tickets and apply status changes in bulk. Is this on the roadmap?",
    status: TicketStatus.Closed,
    category: TicketCategory.General_Question,
    senderName: "Anna Korhonen",
    senderEmail: "anna.korhonen@fi.com",
    createdAt: daysAgo(70),
  },
  {
    subject: "Receipts not including my company address",
    body: "My company address isn't showing on receipts. I've added it in billing settings but it doesn't appear on PDFs.",
    status: TicketStatus.Open,
    category: TicketCategory.General_Question,
    senderName: "Daniel Obi",
    senderEmail: "daniel.obi@businessng.com",
    createdAt: daysAgo(2),
  },
  {
    subject: "Security concern — unusual login from another country",
    body: "I received an alert about a login from Brazil but I'm in Canada. I've changed my password. What else should I do?",
    status: TicketStatus.Resolved,
    category: TicketCategory.Technical_Question,
    senderName: "Zoe Campbell",
    senderEmail: "zoe.campbell@ca.com",
    createdAt: daysAgo(13),
  },
  {
    subject: "Subscription auto-renewed without reminder",
    body: "My yearly subscription renewed and I wasn't reminded beforehand. I'd like to cancel and get a refund.",
    status: TicketStatus.Open,
    category: TicketCategory.Refund_Request,
    senderName: "Martin Svensson",
    senderEmail: "martin.svensson@se.net",
    createdAt: daysAgo(1),
  },
  {
    subject: "Printed materials not matching digital preview",
    body: "The business cards I ordered look very different from the online preview — wrong font and color. Order #77412.",
    status: TicketStatus.Open,
    category: TicketCategory.General_Question,
    senderName: "Layla Hassan",
    senderEmail: "layla.hassan@design.ae",
    createdAt: daysAgo(2),
  },
];

function daysAgo(n: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - n);
  // Randomize the time within the day to make sorting more realistic
  d.setHours(Math.floor(Math.random() * 14) + 7);
  d.setMinutes(Math.floor(Math.random() * 60));
  return d;
}

async function seed() {
  console.log(`Seeding ${tickets.length} tickets...`);
  await prisma.ticket.createMany({ data: tickets });
  console.log("Done.");
}

seed()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
